quarkus:
  datasource:
    username: postgres
    password: postgres
    db-kind: postgresql
    reactive:
      url: postgresql://localhost:5432/postgres
  hibernate-orm:
    database:
      generation: drop-and-create